const types = {
  HOME_COUNT_UP: 'HOME_COUNT_UP',
  HOME_COUNT_DOWN: 'HOME_COUNT_DOWN',
  POPUP_SHOW: 'POPUP_SHOW',
  POPUP_HIDE: 'POPUP_HIDE',
  SEARCH_OVERLAY_TOGGLE: 'SEARCH_OVERLAY_TOGGLE', // 검색어 입력 오버레이 토클.
  SEARCH_FILTER_UPDATE: 'SEARCH_FILTER_UPDATE', // 필터 리스트 업데이
  // TODO 추가 타입 작성.

  //REGISTER WH
  UPLOAD_IMAGE_REGISTER: 'UPLOAD_IMAGE_REGISTER',
  REMOVE_IMAGE_REGISTER: 'REMOVE_IMAGE_REGISTER',
};

export default types;
