const types = {
  HOME_COUNT_UP: 'HOME_COUNT_UP',
  HOME_COUNT_DOWN: 'HOME_COUNT_DOWN',
  POPUP_SHOW: 'POPUP_SHOW',
  POPUP_HIDE: 'POPUP_HIDE',
  SEARCH_OVERLAY_TOGGLE: 'SEARCH_OVERLAY_TOGGLE',
  // TODO 추가 타입 작성.
};

export default types;
